import type { NextPage } from 'next'
import Link from 'next/link'
import Head from 'next/head'
import Layout from '../components/Layout'

const FirstPost: NextPage = () => {

  return (
    <Layout home={false}>
      <Head>
        <title>FirstPost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>first post</h1>
      <p>
        <Link href={'/'}><a>Back to Home</a></Link>
      </p>
      <img src="/vercel.svg" alt="" />
    </Layout>
  )
}

export default FirstPost